version: "3.8"

services:
  app:
    build: .
    container_name: my-app
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:qwerty1234@postgres:5432/Test?schema=public"
    command: ["npm", "run", "start:migrate"]

  postgres:
    image: postgres:13
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty1234
      POSTGRES_DB: Test
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
